# fly.toml app configuration file generated for data-sharing-prod on 2024-01-08T09:14:11+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "data-sharing-prod"
primary_region = "fra"
console_command = "/code/manage.py shell"

[processes]  # <-- Updated!
  app = "python -m gunicorn --bind :8000 --workers 2 data_sharing.wsgi"
  worker = "python -m celery -A web_app worker -l INFO"

[build]

[deploy]
  release_command = "python manage.py migrate --noinput"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = "/code/staticfiles"
  url_prefix = "/static/"
