# Generated by Django 4.2.7 on 2023-11-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadrequest',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadrequest',
            name='file_type',
            field=models.CharField(blank=True, choices=[('CSV', 'CSV'), ('PDF', 'PDF')], max_length=50, null=True),
        ),
    ]
