# Generated by Django 4.2.7 on 2023-12-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_rename_name_space_title_uploadrequest_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='googledrive',
            name='token',
            field=models.CharField(default='ahaha', max_length=255),
            preserve_default=False,
        ),
    ]
