# Generated by Django 4.2.7 on 2023-11-23 18:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=50)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='web_app.space')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
