# Generated by Django 4.2.7 on 2023-12-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_googledrive_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='space',
            options={},
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.UniqueConstraint(models.F('user'), models.F('title'), name='unique_space_title'),
        ),
    ]
