# Generated by Django 4.2.7 on 2023-11-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_space_instructions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='number_of_files',
            new_name='file_number',
        ),
        migrations.AddField(
            model_name='request',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='max_file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
