# Generated by Django 4.2.7 on 2023-12-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_alter_space_options_space_unique_space_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
