# Generated by Django 4.2.9 on 2024-01-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_betaaccessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='betaaccessrequest',
            name='user_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='betaaccessrequest',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='betaaccessrequest',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='betaaccessrequest',
            name='first_touchpoint',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='betaaccessrequest',
            name='industry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
