# Generated by Django 4.2.7 on 2023-12-04 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_app', '0005_alter_space_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spaces', to=settings.AUTH_USER_MODEL),
        ),
    ]
