# Generated by Django 4.2.9 on 2024-02-06 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_remove_user_organization_userorganization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadrequest',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='uploadrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='senderevent',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='web_app.uploadrequest'),
        ),
    ]
