# Generated by Django 4.2.7 on 2023-12-04 14:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_alter_space_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extension', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='uploadrequest',
            name='file_type',
        ),
        migrations.CreateModel(
            name='UploadRequestFileType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_requests', to='web_app.filetype')),
                ('upload_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_types', to='web_app.uploadrequest')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
