# Generated by Django 4.2.9 on 2024-02-06 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_remove_uploadrequest_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='senderevent',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='web_app.space'),
        ),
    ]
