# Generated by Django 4.2.7 on 2023-12-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
