# Generated by Django 4.2.7 on 2023-12-06 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_space_timezone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='space',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='uploadrequest',
            old_name='file_name',
            new_name='file_naming_formula',
        ),
    ]
