# Generated by Django 4.2.9 on 2024-02-10 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_sharepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='senderevent',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='web_app.genericdestination'),
        ),
    ]
