# Generated by Django 4.2.7 on 2023-12-08 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0011_alter_space_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetype',
            name='upload_requests',
            field=models.ManyToManyField(through='web_app.UploadRequestFileType', to='web_app.uploadrequest'),
        ),
        migrations.AddField(
            model_name='uploadrequest',
            name='file_types',
            field=models.ManyToManyField(through='web_app.UploadRequestFileType', to='web_app.filetype'),
        ),
        migrations.AlterField(
            model_name='uploadrequestfiletype',
            name='file_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.filetype'),
        ),
        migrations.AlterField(
            model_name='uploadrequestfiletype',
            name='upload_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.uploadrequest'),
        ),
    ]
