# Generated by Django 4.2.9 on 2024-02-10 10:44
from django.contrib.postgres.operations import TrigramExtension
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    operations = [TrigramExtension()]
    dependencies = [
        ('web_app', '0012_googledrive_social_account_googledrive_user_and_more')
    ]
