# Generated by Django 4.2.7 on 2023-12-08 14:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0012_filetype_upload_requests_uploadrequest_file_types_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderEvent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('FILE_UPLOADED', 'File uploaded')], max_length=100)),
                ('data', models.JSONField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.uploadrequest')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.sender')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
