# Generated by Django 4.2.7 on 2023-12-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0013_senderevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddConstraint(
            model_name='uploadrequest',
            constraint=models.UniqueConstraint(models.F('title'), models.F('space'), name='unique_request_title'),
        ),
    ]
