# Generated by Django 4.2.9 on 2024-02-11 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0014_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='web_app.contact'),
        ),
    ]
