# Generated by Django 4.2.7 on 2023-12-11 16:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0015_customuser_remove_googledrive_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_name', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('file_type', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='senderevent',
            name='data',
        ),
        migrations.AlterField(
            model_name='genericdestination',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='web_app.uploadrequest'),
        ),
        migrations.AddField(
            model_name='senderevent',
            name='file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.file'),
        ),
    ]
