# Generated by Django 4.2.9 on 2024-02-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0016_alter_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendernotificationssettings',
            name='language',
            field=models.CharField(default='en-us', max_length=10),
        ),
    ]
