# Generated by Django 5.0 on 2023-12-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0016_file_remove_senderevent_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericdestination',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
