# Generated by Django 5.0 on 2023-12-12 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0017_genericdestination_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_name',
            new_name='name',
        ),
    ]
