# Generated by Django 4.2.9 on 2024-02-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0017_sendernotificationssettings_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
