# Generated by Django 5.0 on 2023-12-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0018_rename_file_name_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='google_drive_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
