# Generated by Django 4.2.9 on 2024-02-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0020_file_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadrequest',
            name='file_template',
            field=models.URLField(blank=True, null=True),
        ),
    ]
