# Generated by Django 5.0 on 2023-12-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0021_alter_senderevent_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='deadline_reminder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='notify_deadline',
            field=models.BooleanField(default=False),
        ),
    ]
