# Generated by Django 4.2.9 on 2024-02-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0021_uploadrequest_file_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
