# Generated by Django 5.0 on 2023-12-18 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0022_space_deadline_reminder_space_notify_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='deadline_reminder',
        ),
    ]
