# Generated by Django 5.0 on 2023-12-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0023_remove_space_deadline_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadrequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
