# Generated by Django 5.0 on 2023-12-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0024_space_is_deleted_uploadrequest_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetype',
            name='slug',
            field=models.CharField(default='csv', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
