# Generated by Django 4.2.9 on 2024-02-18 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import web_app.storage_backends.backends


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0025_file_upload_file_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kezyy',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='file',
            name='upload',
        ),
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
        migrations.CreateModel(
            name='KezyyFile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.FileField(storage=web_app.storage_backends.backends.PrivateMediaStorage(), upload_to='')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='web_app.kezyy')),
                ('file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kezyy_file', to='web_app.file')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
