# Generated by Django 5.0 on 2023-12-20 14:12

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):
    dependencies = [
        ('web_app', '0025_filetype_slug'),
]
    operations = [TrigramExtension()]
