# Generated by Django 4.2.9 on 2024-02-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0026_kezyy_remove_file_upload_remove_file_user_kezyyfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
