# Generated by Django 5.0 on 2023-12-26 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0026_trigram_extension'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='uploadrequest',
            name='unique_request_title',
        ),
        migrations.AddField(
            model_name='filetype',
            name='group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filetype',
            name='group_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.filetype'),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='extension',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
