# Generated by Django 4.2.9 on 2024-02-18 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0027_alter_file_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='url',
            new_name='_url',
        ),
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.AddField(
            model_name='file',
            name='_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='web_app.genericdestination'),
        ),
        migrations.AddField(
            model_name='file',
            name='uid',
            field=models.CharField(default='noid', max_length=255),
        ),
    ]
