# Generated by Django 4.2.9 on 2024-02-18 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0028_rename_url_file__url_remove_file_name_file__name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='_name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='_url',
        ),
    ]
