# Generated by Django 5.0 on 2024-01-11 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0029_space_deadline_enforced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='deadline_enforced',
            new_name='upload_after_deadline',
        ),
    ]
