# Generated by Django 5.0 on 2024-01-12 17:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0030_rename_deadline_enforced_space_upload_after_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senderevent',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='sender_event',
            field=models.ForeignKey(default=uuid.UUID('a892143c-bbc9-4848-99d2-a32003f05680'), on_delete=django.db.models.deletion.CASCADE, related_name='files', to='web_app.senderevent'),
        ),
    ]
