# Generated by Django 5.0 on 2024-01-12 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0031_remove_senderevent_file_file_sender_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='senderevent',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='sender_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='web_app.senderevent'),
        ),
    ]
