# Generated by Django 4.2.9 on 2024-02-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0032_alter_organizationinvitation_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
