# Generated by Django 5.0 on 2024-01-17 07:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0032_senderevent_notes_alter_file_sender_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='deadline_notice_days',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('15'))]),
        ),
        migrations.AddField(
            model_name='space',
            name='deadline_notice_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('23.9'))]),
        ),
    ]
