# Generated by Django 5.0 on 2024-01-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0033_space_deadline_notice_days_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='space',
            name='unique_space_title',
        ),
    ]
