# Generated by Django 4.2.9 on 2024-02-29 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0033_alter_space_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericdestination',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
