# Generated by Django 5.0 on 2024-01-18 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0034_remove_space_unique_space_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='is_active',
        ),
    ]
