# Generated by Django 4.2.9 on 2024-03-01 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0035_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spaces', to='web_app.company'),
        ),
    ]
