# Generated by Django 5.0 on 2024-01-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0035_remove_space_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='notify_invitation',
            field=models.BooleanField(default=False),
        ),
    ]
