# Generated by Django 5.0 on 2024-01-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0036_space_notify_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='deadline_notice_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='deadline_notice_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
