# Generated by Django 5.0 on 2024-01-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0037_alter_space_deadline_notice_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='deadline_notification_datetime',
            field=models.GeneratedField(db_persist=True, expression=models.F('deadline'), output_field=models.DateTimeField()),
        ),
    ]
