# Generated by Django 4.2.9 on 2024-03-04 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0038_remove_uploadrequestfiletype_file_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='company',
        ),
    ]
