# Generated by Django 5.0 on 2024-01-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0038_space_deadline_notification_datetime'),
    ]

    operations = []
