# Generated by Django 4.2.9 on 2024-03-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0040_contact_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set(),
        ),
    ]
