# Generated by Django 5.0 on 2024-01-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0040_sender_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='locale',
            field=models.CharField(blank=True, default='en-us', max_length=10, null=True),
        ),
    ]
