# Generated by Django 5.0 on 2024-01-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0041_space_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadrequest',
            name='multiple_files',
            field=models.BooleanField(default=False),
        ),
    ]
