# Generated by Django 4.2.9 on 2024-03-05 10:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0042_request_remove_uploadrequest_instructions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputRequest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ManyToManyField(related_name='input_requests', to='web_app.request')),
                ('text_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.textrequest')),
                ('upload_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.request')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
