# Generated by Django 5.0 on 2024-01-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0043_onedrive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='google_drive_url',
            new_name='url',
        ),
    ]
