# Generated by Django 4.2.9 on 2024-03-05 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0043_inputrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputrequest',
            name='upload_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.uploadrequest'),
        ),
    ]
