# Generated by Django 5.0 on 2024-01-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0044_rename_google_drive_url_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='invited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
