# Generated by Django 4.2.9 on 2024-03-05 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0044_alter_inputrequest_upload_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputrequest',
            name='request',
        ),
        migrations.AddField(
            model_name='inputrequest',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_requests', to='web_app.request'),
        ),
    ]
