# Generated by Django 5.0.1 on 2024-01-23 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('web_app', '0045_sender_invited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='notification_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask'),
        ),
    ]
