# Generated by Django 4.2.9 on 2024-03-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0045_remove_inputrequest_request_inputrequest_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textrequest',
            old_name='label',
            new_name='title',
        ),
        migrations.AddField(
            model_name='uploadrequest',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
