# Generated by Django 4.2.9 on 2024-03-06 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0046_rename_label_textrequest_title_uploadrequest_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senderevent',
            name='request',
        ),
        migrations.AddField(
            model_name='senderevent',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='senderevent',
            name='text_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='web_app.textrequest'),
        ),
        migrations.AlterField(
            model_name='senderevent',
            name='event_type',
            field=models.CharField(choices=[('FILE_UPLOADED', 'File uploaded'), ('TEXT_CREATED', 'Text created')], max_length=100),
        ),
    ]
