# Generated by Django 4.2.9 on 2024-03-06 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0047_remove_senderevent_request_senderevent_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='senderevent',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='web_app.request'),
        ),
        migrations.AddField(
            model_name='senderevent',
            name='upload_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='web_app.uploadrequest'),
        ),
    ]
