# Generated by Django 5.0 on 2024-03-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0048_senderevent_request_senderevent_upload_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='textrequest',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='uploadrequest',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
