# Generated by Django 5.0 on 2024-03-08 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0051_company_address_company_reference_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='web_app.company'),
        ),
    ]
