# Generated by Django 5.0 on 2024-03-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0052_file_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfield',
            name='value',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
