# Generated by Django 5.0 on 2024-03-09 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0053_alter_companyfield_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyfield',
            name='organization',
        ),
    ]
