# Generated by Django 5.0 on 2024-03-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0054_remove_companyfield_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfield',
            name='label',
            field=models.CharField(max_length=250),
        ),
    ]
