# Generated by Django 5.0 on 2024-03-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0057_request_is_active_request_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='textrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='textrequest',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadrequest',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
