# Generated by Django 5.0 on 2024-03-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0058_remove_request_is_completed_textrequest_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textrequest',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='textrequest',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='uploadrequest',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='uploadrequest',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='inputrequest',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inputrequest',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
