# Generated by Django 5.0 on 2024-03-11 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0061_filesection_file_filesection_space_textsection_space'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesection',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='genericdestination',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='web_app.space'),
        ),
        migrations.AlterField(
            model_name='file',
            name='sender_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='web_app.senderevent'),
        ),
        migrations.AlterField(
            model_name='genericdestination',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='web_app.uploadrequest'),
        ),
    ]
