# Generated by Django 5.0 on 2024-03-11 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0062_rename_content_filesection_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendernotificationssettings',
            name='user',
        ),
        migrations.AddField(
            model_name='sendernotificationssettings',
            name='organization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_notifications_settings', to='web_app.organization'),
        ),
    ]
