# Generated by Django 5.0 on 2024-03-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0063_remove_sendernotificationssettings_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputrequest',
            old_name='is_completed',
            new_name='is_complete',
        ),
    ]
