# Generated by Django 5.0 on 2024-03-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0064_rename_is_completed_inputrequest_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='textrequest',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadrequest',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
