# Generated by Django 5.0 on 2024-03-13 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0067_remove_file_status_remove_textoutput_status_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputrequest',
            name='text_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_request', to='web_app.textrequest'),
        ),
        migrations.AlterField(
            model_name='inputrequest',
            name='upload_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_request', to='web_app.uploadrequest'),
        ),
    ]
