# Generated by Django 5.0 on 2024-03-14 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0068_alter_inputrequest_text_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='space',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='web_app.organization'),
        ),
    ]
