# Generated by Django 5.0 on 2024-03-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0070_alter_file_sender_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='space',
            name='deadline_notice_days',
        ),
        migrations.RemoveField(
            model_name='space',
            name='deadline_notice_hours',
        ),
        migrations.RemoveField(
            model_name='space',
            name='notify_deadline',
        ),
        migrations.RemoveField(
            model_name='space',
            name='notify_invitation',
        ),
        migrations.RemoveField(
            model_name='space',
            name='upload_after_deadline',
        ),
        migrations.AddField(
            model_name='request',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='deadline_notice_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='deadline_notice_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='notify_deadline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='upload_after_deadline',
            field=models.BooleanField(default=False),
        ),
    ]
