# Generated by Django 5.0.3 on 2024-03-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0071_remove_space_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfield',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
