# Generated by Django 5.0 on 2024-03-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0075_companyfield_multiple_alter_companyfield_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfield',
            name='counter',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
