# Generated by Django 5.0 on 2024-03-28 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0076_companyfield_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfieldgroup',
            name='counter',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='companytemplate',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='web_app.companyfield'),
        ),
        migrations.AddField(
            model_name='companytemplate',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='web_app.companyfieldgroup'),
        ),
        migrations.AlterField(
            model_name='companytemplate',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
