# Generated by Django 5.0 on 2024-03-28 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0078_remove_companyfield_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfield',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_fields', to='web_app.organization'),
        ),
        migrations.AddField(
            model_name='companyfieldgroup',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_field_groups', to='web_app.organization'),
        ),
    ]
