# Generated by Django 5.0.3 on 2024-03-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0079_companyfield_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='alias',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='application_page_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='de_minimis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grant',
            name='descriptive_admitted_expenses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='descriptive_allowed_activities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='descriptive_application_iter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='descriptive_beneficiaries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='descriptive_funds',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='descriptive_goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='descriptive_not_admitted_expenses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='descriptive_other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='descriptive_timeline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='financer_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='financer_website_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='official_page_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
