# Generated by Django 5.0.3 on 2024-03-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0080_grant_alias_grant_application_page_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='alias',
        ),
        migrations.AddField(
            model_name='grant',
            name='official_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
