# Generated by Django 5.0.3 on 2024-03-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0081_remove_grant_alias_grant_official_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='status',
            field=models.CharField(choices=[('Announced', 'Announced'), ('Published', 'Published'), ('Closed', 'Closed')], default='Announced', max_length=50),
        ),
    ]
