# Generated by Django 5.0.3 on 2024-04-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0082_grant_support_email_alter_grant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='de_minimis',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
