# Generated by Django 5.0 on 2024-04-02 12:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0083_alter_grant_de_minimis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companygroupelement',
            name='field',
        ),
        migrations.RemoveField(
            model_name='companytemplate',
            name='field',
        ),
        migrations.RemoveField(
            model_name='companytemplate',
            name='name',
        ),
        migrations.AlterField(
            model_name='companyfieldgroup',
            name='template',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='web_app.companytemplate'),
        ),
        migrations.AlterField(
            model_name='companytemplate',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_template', to='web_app.companyfieldgroup'),
        ),
        migrations.CreateModel(
            name='CompanyTextField',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('multiple', models.BooleanField(default=False)),
                ('label', models.CharField(max_length=250)),
                ('value', models.CharField(blank=True, max_length=500, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='web_app.company')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='web_app.companyfieldgroup')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='companygroupelement',
            name='text_field',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element', to='web_app.companytextfield'),
        ),
        migrations.CreateModel(
            name='GrantAttachment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grant_attachment', to='web_app.file')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CompanyField',
        ),
    ]
