# Generated by Django 5.0 on 2024-04-02 14:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0084_remove_companygroupelement_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('output', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='web_app.output')),
                ('text_field', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='web_app.companytextfield')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
