# Generated by Django 5.0 on 2024-04-03 07:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0086_textrequest_target_delete_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companytemplate',
            name='group',
        ),
        migrations.RemoveField(
            model_name='companytextfield',
            name='group',
        ),
        migrations.RemoveField(
            model_name='companygroupelement',
            name='parent_group',
        ),
        migrations.RemoveField(
            model_name='companygroupelement',
            name='group',
        ),
        migrations.RemoveField(
            model_name='companygroupelement',
            name='text_field',
        ),
        migrations.RemoveField(
            model_name='companytemplate',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='companytextfield',
            name='company',
        ),
        migrations.CreateModel(
            name='FieldGroup',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('multiple', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, max_length=250, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_groups', to='web_app.company')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='web_app.fieldgroup')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_groups', to='web_app.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldGroupTemplate',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_template', to='web_app.fieldgroup')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_group_templates', to='web_app.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fieldgroup',
            name='template',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='web_app.fieldgrouptemplate'),
        ),
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('multiple', models.BooleanField(default=False)),
                ('label', models.CharField(max_length=250)),
                ('value', models.CharField(blank=True, max_length=500, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='web_app.company')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='web_app.fieldgroup')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupElement',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(default=1)),
                ('text_field', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element', to='web_app.textfield')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='textrequest',
            name='target',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='web_app.textfield'),
        ),
        migrations.DeleteModel(
            name='CompanyFieldGroup',
        ),
        migrations.DeleteModel(
            name='CompanyGroupElement',
        ),
        migrations.DeleteModel(
            name='CompanyTemplate',
        ),
        migrations.DeleteModel(
            name='CompanyTextField',
        ),
    ]
