# Generated by Django 5.0 on 2024-04-03 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0087_remove_companytemplate_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupelement',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element', to='web_app.fieldgroup'),
        ),
        migrations.AddField(
            model_name='groupelement',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_elements', to='web_app.fieldgroup'),
        ),
    ]
