# Generated by Django 5.0 on 2024-04-05 08:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0088_groupelement_group_groupelement_parent_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantDeadline',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('sender_visibility', models.BooleanField(default=False)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='web_app.grant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='GrantAttachment',
        ),
    ]
