# Generated by Django 5.0 on 2024-04-05 08:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0089_grantdeadline_delete_grantattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantAttachment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grant_attachment', to='web_app.file')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='web_app.grant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
