# Generated by Django 5.0 on 2024-04-05 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0090_grantattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textfield',
            name='company',
        ),
    ]
