# Generated by Django 5.0 on 2024-04-05 09:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0091_remove_textfield_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfield',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_fields', to='web_app.fieldgroup'),
        ),
        migrations.CreateModel(
            name='FileField',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('multiple', models.BooleanField(default=False)),
                ('label', models.CharField(max_length=250)),
                ('multiple_files', models.BooleanField(default=False)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_fields', to='web_app.fieldgroup')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
