# Generated by Django 5.0 on 2024-04-05 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0092_alter_textfield_group_filefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupelement',
            name='file_field',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element', to='web_app.filefield'),
        ),
    ]
