# Generated by Django 5.0 on 2024-04-08 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0095_space_grant_space_source_grant_uploadrequest_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='grant',
        ),
        migrations.AddField(
            model_name='grant',
            name='space',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grant', to='web_app.space'),
        ),
    ]
