# Generated by Django 5.0 on 2024-04-08 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0096_remove_space_grant_grant_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldgroup',
            name='grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_groups', to='web_app.grant'),
        ),
    ]
