# Generated by Django 5.0 on 2024-04-08 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0097_fieldgroup_grant'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputrequest',
            name='child_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_request', to='web_app.request'),
        ),
        migrations.AddField(
            model_name='request',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_requests', to='web_app.request'),
        ),
    ]
