# Generated by Django 5.0 on 2024-04-08 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0098_inputrequest_child_request_request_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefilefield',
            name='template',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_field_template', to='web_app.file'),
        ),
    ]
