# Generated by Django 5.0 on 2024-04-09 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0099_filefilefield_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefield',
            name='fill_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filling_fields', to='web_app.filefield'),
        ),
        migrations.AddField(
            model_name='textfield',
            name='fill_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filling_fields', to='web_app.textfield'),
        ),
    ]
