# Generated by Django 5.0 on 2024-04-09 08:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0100_filefield_fill_from_textfield_fill_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldTemplate',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_field', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_template', to='web_app.filefield')),
                ('group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_template', to='web_app.fieldgroup')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_group_templates', to='web_app.organization')),
                ('text_field', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_template', to='web_app.textfield')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='filefield',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_fields', to='web_app.fieldtemplate'),
        ),
        migrations.AddField(
            model_name='textfield',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_fields', to='web_app.fieldtemplate'),
        ),
        migrations.AlterField(
            model_name='fieldgroup',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='web_app.fieldtemplate'),
        ),
        migrations.DeleteModel(
            name='FieldGroupTemplate',
        ),
    ]
