# Generated by Django 5.0 on 2024-04-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0101_fieldtemplate_filefield_template_textfield_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtemplate',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
